services:
  - type: web
    name: ai-image-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: MONGODB_URI
        sync: false 